### ISSUE TITLE
Corrupted output files

### ISSUE THREAD

**Issue by zatherz** [hcs64/ww2ogg#10]
The conversion output looks fine:
```
Input: ./852555435.wem
RIFF WAVE 2 channels 44100 Hz 90856 bps
6804001 samples
- 2 byte packet headers, no granule
- stripped setup header
- external codebooks (packed_codebooks.bin)
- modified Vorbis packets
Output: ogg/./852555435.wem.ogg
Done!

```

However, when trying to open the file with VLC, it complains with `3rd Vorbis header is corrupted`. MPlayer plays random garbage.

Game is [Enter the Gungeon](http://enterthegungeon.com).

**Solution**: Use the `--pcb packed_codebooks_aoTuV_603.bin` option, then use revorb on the output oggs.

**Comment by hcs64** [comment]
Have you tried the troubleshooting steps listed in the README? You should at least try `--no-mod-packets` and `--pcb packed_codebooks_aoTuV_603.bin`.

**Comment by zatherz** [comment]
After adding `--pcb ../ww2ogg/packed_codebooks_aoTuV_603.bin` to the command, the error doesn't happen anymore, but nothing plays (VLC stops playing it instantly). Here is an example file: https://ptpb.pw/6I4r.ogg.

`--no-mod-packets` has no effect (3rd vorbis header is corrupted without the `--pcb`, nothing plays with the `--pcb`).

**Comment by zatherz** [comment]
UPDATE: MPlayer successfully plays the file.

```
Mismatching header version 57.56.100
libavformat file format detected.
[ogg @ 0x7f1ea8f0bee0]Estimating duration from bitrate, this may be inaccurate

```

**Comment by hcs64** [comment]
You may have better luck with VLC if you run the output through revorb first. I know foobar2000 at least has trouble dealing with the bad granulepos ww2ogg outputs.

**Comment by zatherz** [comment]
Oh wow. Previously revorb just crashed on me. Now it works, and indeed, it works in VLC too. Thank you so much for the help!
