### ISSUE TITLE
Parse error: expected 0x42 fmt if vorb missing

### ISSUE THREAD

**Issue by Kilowog01** [hcs64/ww2ogg#14]
When trying to convert 528 .wav files extracted from Tekken 7 to ogg. Only 3 files convert normally (092, 138 and 289). I've hosted the files so that you can investigate and have a greater chance of success in fixing this. Could you please try to fix it? It would make a giant difference in my life. The password for extraction is: hcs64
https://drive.google.com/open?id=1lz4jKUs9gNrMTgNqUufskpw-nHGDFCzS

**Comment by hcs64** [comment]
I've requested access to the files, but that message usually means that the data isn't Vorbis, so ww2ogg can't convert it.

You may want to try playing the files with [vgmstream](https://hcs64.com/vgmstream.html), which can play many Wwise formats.
