### ISSUE TITLE
Parse error: RIFF truncated

### ISSUE THREAD

**Issue by MarcoDotIO** [hcs64/ww2ogg#18]
I'm having an issue converting a batch of wem files into an ogg format, with this following error being the output for every file:

`Parse error: RIFF truncated`

Here's the input of each conversion:

`ww2ogg.exe n.wem --pcb packed_codebooks_aoTuV_603.bin
Audiokinetic Wwise RIFF/RIFX Vorbis to Ogg Vorbis converter 0.22 by hcs`
(n being a number)

I will give any other information, if needed, for troubleshooting. I know that the ww2ogg executable was grabbed from the latest build.

**Comment by hcs64** [comment]
This can be the case when the files haven't been extracted right, or when the stream is split into a resident header and a separate streaming body that has to be located in some other file. I can't really provide much support for extraction here, but if you can say what the game is someone else might have advice, here or on [my forum](https://hcs64.com/mboard/forum.php).

**Comment by hcs64** [comment]
Some more detail can be found [on the forum](https://hcs64.com/mboard/forum.php?showthread=61083), I don't think this is a ww2ogg issue. Sorry I can't be of more help.
