### ISSUE TITLE
Baldur's Gate 3 .wem files don't convert 

### ISSUE THREAD

**Issue by PKBeam** [hcs64/ww2ogg#19]
Previously the alternate packed codebooks worked, but a recent update to the game has changed this.

This is what ww2ogg outputs now for both normal and alternate packed codebooks.
```
Input: .\13734.wem
RIFF WAVE 2 channels 48000 Hz 297208 bps
18048000 samples
- 6 byte packet headers, no granule
- stripped setup header
- external codebooks
- shortened Vorbis packets
Output: .\13734.ogg
Parse error: invalid floor1 masterbook
```

I've attached an example file:
[13734.zip](https://github.com/hcs64/ww2ogg/files/5484341/13734.zip)
vgmstream does not play this file.

**Comment by PKBeam** [comment]
Okay, I have to apologise.
The wem file I was working with was incorrectly extracted.
After re-extracting the file properly, the alternate packed codebooks work now.

**Comment by hcs64** [comment]
Thanks for the follow-up, sorry I didn't get a chance to look into it sooner.
