### ISSUE TITLE
[Request] Trine 3 WEM support

### ISSUE THREAD

**Issue by Kein** [hcs64/ww2ogg#2]
ww2ogg.exe audio1_fbq-0000000187.wem -o 1.ogg --pcb packed_codebooks_aoTuV_603.bin
Audiokinetic Wwise RIFF/RIFX Vorbis to Ogg Vorbis converter 0.22 by hcs
Input: audio1_fbq-0000000187.wem
Parse error: expected 0x42 fmt if vorb missing

http://i.imgur.com/l3EBqou.png

**Comment by hcs64** [comment]
I can't tell for sure based on just the screenshot you sent, but it looks like the file is not Vorbis data. It appears to be 16-bit little endian PCM, which you can read with many raw audio editors.

**Comment by Catarax** [comment]
Tips : Use GoldWave 16 bits signed, stereo to play the file.

**Comment by shmerl** [comment]
I have a similar problem with System Shock Demo audio. I extracted WEM files using

```
Parse error: expected 0x42 fmt if vorb missing bnkextr, and when running ww2ogg I get:

ww2ogg 0001.wem 
Audiokinetic Wwise RIFF/RIFX Vorbis to Ogg Vorbis converter 0.24 by hcs

Input: 0001.wem
Parse error: expected 0x42 fmt if vorb missing
```

Here is the screenshot of the hex header:

![hex_header](https://cloud.githubusercontent.com/assets/310927/17003094/6575aec6-4e9c-11e6-989b-3dd5711efedf.png)

I can't open this file with Audacity.

**Comment by shmerl** [comment]
OK, I figured, Audacity doesn't analyze it by default. I had to do explicit raw import.

**Comment by shmerl** [comment]
Here is a final example using sox (for System Shock Demo):

```
sox --type raw --rate 44100 --encoding signed --endian little --bits 16 --channels 2 0001.wem 0001.wav
```

**Comment by hcs64** [comment]
@shmerl : You'll want to skip the 64 (0x40) bytes of header.

Use Audacity Import->Raw Data with Start Offset set to 64.

Or with sox and dd and pipes:

``` sh
dd if=0001.wem ibs=64 skip=1 | sox --type raw --rate 44100 --encoding signed --endian little --bits 16 --channels 2 - 0001.wav
```
