### ISSUE TITLE
Inverse?

### ISSUE THREAD

**Issue by isobellavt** [hcs64/ww2ogg#20]
I know this is an old project, but, is there any chance of making the inverse? Converting a .ogg to a .wem?

**Comment by hcs64** [comment]
No, that would be out of scope for this project. Additionally, it could only ever work on a very limited range of input Oggs, as the Wwise encoding uses a particular set of codebooks (which might be everything possible for a given encoder, but I'm not sure). It should be possible to use the Wwise SDK to get files in the right format.
