### ISSUE TITLE
Is there is a way to do the conversion in reverse?

### ISSUE THREAD

**Issue by St0RM53** [hcs64/ww2ogg#24]
I've managed to convert WEM files from God of War PC and fix them with revorb, but my end goal is to change the audio to my own and put it back in the game. Is this possible?

example (this is kratos voice in greek from the first hour of gameplay: https://www.dropbox.com/s/ing9ghoi809uq0n/252692446.wem?dl=0 )

**Comment by hcs64** [comment]
I'm not aware of any tools besides Wwise itself that support this, I think you can still get a trial version at https://www.audiokinetic.com/products/wwise/

It will be tricky to get it into the right format for the game you're trying to mod. I'm sure there are projects out there for modding Wwise audio, but I don't know about them. In any case it it won't be directly related to ww2ogg.

Some examples from a quick search, these won't be directly applicable but might give you an idea of what to try:

* No Man's Sky: https://www.nexusmods.com/nomanssky/mods/195/
* RE2 Remake: https://residentevilmodding.boards.net/thread/10211/method-audio-modding
* Civ6: https://forums.civfanatics.com/threads/wwise-editor-2015-1-9-needed-for-audio-modding.610973/

**Comment by St0RM53** [comment]
Thanks a lot! I'll have a look and see what i can manage to do! What i am wondering is if i have to re-code the file somehow in order for it to work properly. Either way, i'll give my best try and if i need some advice i can re-contact you :)
