### ISSUE TITLE
Parse error: expected 0x42 fmt if vorb missing

### ISSUE THREAD

**Issue by Zemogiter** [hcs64/ww2ogg#26]
This error happens when trying to convert some `.wem` files (obviously cant share them because of copyright reasons). The error is consistend i.e. the same files give the same error.
I'm using a batch file to convert all of them:
```
for %%f in (*.wem) do "./ww2ogg.exe" %%f --pcb "./packed_codebooks_aoTuV_603.bin"
pause
for %%f in (*.ogg) do revorb.exe %%f
pause
```

**Comment by SullyPanda76cl** [comment]
same problem here.
why is this issue closed?

**Comment by hcs64** [comment]
> same problem here. why is this issue closed?

As the readme notes:

> `Parse error: expected 0x42 fmt if vorb missing` suggests that the input is not Vorbis data at all, and so it is not supported by this program.

I suggest trying to decode the file with [vgmstream](https://vgmstream.org/), it supports more formats, and it will tell you what codec is used.
