### ISSUE TITLE
Output file is corrupted and cannot be interacted with

### ISSUE THREAD

**Issue by Agent-Maxwell** [hcs64/ww2ogg#27]
When converting any of the sound files from Prey (2017) the output is unusable. The resulting .ogg is unable to be played and if right clicked crashes windows explorer. I have tried both of the recommended troubleshooting steps. ReVorb also has no effect on the file.

cmd output:
> Input: test.wem
RIFF WAVE 1 channel 44100 Hz 113968 bps
122621 samples 
-2 byte packet headers, no granule
-stripped setup header
-external codebooks (packed_codebooks_aoTuV_603.bin)
-modified Vorbis packets
Output: test.ogg

**Comment by hcs64** [comment]
How did you obtain the .wems? You might try using the steps listed [here](https://www.reddit.com/r/prey/comments/nvdet0/currently_working_method_of_extracting_audio_files/) for extraction in case the decryption (for the Steam version) didn't work correctly; there were three versions of [the decryption tool](https://forum.xentax.com/viewtopic.php?f=10&t=16241).

If you are confident the extraction was correct, please upload a sample .wem and I can take a look.

**Comment by Agent-Maxwell** [comment]
I did use that tool to get the wems, I will send a sample (had to zip it cause github doesn't support the filetype). Thanks for the help.
[samplewem.zip](https://github.com/hcs64/ww2ogg/files/11124020/samplewem.zip)

**Comment by hcs64** [comment]
That file seems to convert ok here with the [current release](https://github.com/hcs64/ww2ogg/releases/tag/0.24) (0.24) on Windows:

```
C:\Users\WDAGUtilityAccount\Desktop>ww2ogg 3150912.wem --pcb packed_codebooks_aoTuV_603.bin
Audiokinetic Wwise RIFF/RIFX Vorbis to Ogg Vorbis converter 0.24 by hcs

Input: 3150912.wem
RIFF WAVE 2 channels 44100 Hz 194304 bps
330750 samples
- 2 byte packet headers, no granule
- stripped setup header
- external codebooks (packed_codebooks_aoTuV_603.bin)
- modified Vorbis packets
Output: 3150912.ogg
Done!
```

[Output](https://github.com/hcs64/ww2ogg/files/11125582/3150912.zip) is attached, including a rebuild with revorb which works in VLC and Firefox. Both work ok in Edge, foobar2000, or Audacity. (Though there's not much here, just an ambient beat)

Also I should mention: [vgmstream](https://vgmstream.org/) supports this natively, without having to produce .ogg output, if you don't want to bother converting the files.

**Comment by Agent-Maxwell** [comment]
Very strange, when I try and open the file you sent it crashes windows explorer as well. 

Ok I've done a google search and it appears that Windows has a program that it sometimes installs, and said program makes .ogg files crash windows explorer. I apologize for wasting your time and I curse the name of Bill Gates forevermore.
