### ISSUE TITLE
Get expected 0x42 while input from the Baldur's Gate 3

### ISSUE THREAD

**Issue by eviluess** [hcs64/ww2ogg#29]
Hey, good job, man!

And I tried this tool using both pcb and got the following error :
Parse error: expected 0x42 fmt if vorb missing

The file is from Baldur's Gate 3.

Do you have a plan to upgrade this tool?

Thanks in advance.
[758664857.zip](https://github.com/hcs64/ww2ogg/files/13749243/758664857.zip)

**Comment by eviluess** [comment]
You don't need to be rush; I found a foobar component can do this:
https://www.foobar2000.org/components/view/foo_input_vgmstream

**Comment by hcs64** [comment]
BG3 uses Opus, ww2ogg only works with Vorbis. It's not impossible that Opus support could be added, but it's probably a better idea to just use [vgmstream](https://vgmstream.org/) as you discovered, for playing the music without a separate conversion step.
