### ISSUE TITLE
EVE Online new format

### ISSUE THREAD

**Issue by HTL2001** [hcs64/ww2ogg#5]
It appears EVE no longer decodes, I've tried all the combos of packed codebooks and mod packets.

The new resource cache doesn't do extensions, but I separated the audio files using `file`, and copying files that were similar to "RIFF (little-endian) data, WAVE audio, stereo 48000 Hz" (just looked for RIFF).  If needed I can upload some example files.

**Comment by hcs64** [comment]
Do you get any error messages?

Could you point me at some particular file that's problematic? I have the latest EVEResources.7z (md5 `1cfd1f93c5b027c83c14e63c85e82d42`) which I think is from February 25 2016. I didn't find any that didn't decode correctly in that bundle with ww2ogg 0.24 and `--pcb packed_codebooks_aoTuV_603.bin`.

**Comment by HTL2001** [comment]
No error messages, just:

```
Audiokinetic Wwise RIFF/RIFX Vorbis to Ogg Vorbis converter 0.24 by hcs

Input: 001c83a3cd80bd69_c38ebe5ad74196ec98c98be018a269a6
RIFF WAVE 2 channels 48000 Hz 104232 bps
552000 samples
- 2 byte packet headers, no granule
- stripped setup header
- external codebooks (packed_codebooks.bin)
- modified Vorbis packets
Output: 001c83a3cd80bd69_c38ebe5ad74196ec98c98be018a269a6.ogg
```

it results either in the player refusing to play, or for more permissive players, a screechy mess.  Binary pulled from here: https://forums.eveonline.com/default.aspx?g=posts&m=6371200 same md5 (originally I was just pulling from my installed resource cache, same result though)

e: nevermind... somehow I missed that one of my attempts worked.  Still seems to be giving some players issues, and the revorb thing keeps crashing.  But, its not what I though originally.  Thanks for the help

**Comment by HTL2001** [comment]
Sorry don't know if you'll see this, but some of the bnk extracted files actually do give an error, looks like all the 'Turrets' files
`RIFF (little-endian) data, WAVE audio, Microsoft ADPCM, mono 48000 Hz`

```
Audiokinetic Wwise RIFF/RIFX Vorbis to Ogg Vorbis converter 0.24 by hcs

Input: Turrets.053.wav
Parse error: expected 0x42 fmt if vorb missing
```

**Comment by hcs64** [comment]
I assume that Turrets.053.wav came out of `d218fb784d254413_32229fb6eedc544590b4966183525f53`, the extractor I'm using ([bnkextr](https://github.com/eXpl0it3r/bnkextr/)) gives names like 0582.wem but this is one of only two resources with both Turrets and RIFF in it (the other is `7638e3bd52dcedb1_c1e6c93394bbe70cb5d572ceae337bd0` which is just Vorbis).

These files seem to be Wwise IMA ADPCM, you can decode these with wwise_ima_adpcm or ima_rejigger5 as discussed in issue #4. I am having some doubts as to how accurate these are, as when I tried with the largest file there was a lot of clipping, but it was also an explosion so who knows.
