### ISSUE TITLE
Doesn't convert correctly 

### ISSUE THREAD

**Issue by Tachiorz** [hcs64/ww2ogg#9]
Can't figure out why.
Example: https://mega.nz/#!j9VQnSzK!k0KW63S0GSUmDU1oecl8orDf5FwYyS9LsPoeF5gI8Hs

**Comment by hcs64** [comment]
Have you tried everything mentioned in the troubleshooting section of the
readme? I'll check it out when I get a chance, but there may already be an
answer there for you.

**Comment by hcs64** [comment]
I suspect that these files weren't extracted correctly. After 0x10000, the packet sizes are abnormally large, probably just random junk. The extraction may be messing up after the first 0x10000 bytes.

**Comment by Tachiorz** [comment]
But file endings are good. Hmm, both videos and sound were uncompressed in the game package and both are garbled. I guess setting up additional encryption layer was a logical step. 
Sorry for troubling you, and thanks!

**Comment by hcs64** [comment]
No problem, I didn't expect encryption but that seems as likely as
anything. What game is this from?

**Comment by Tachiorz** [comment]
Lineage eternal. There was a bug in the unpacker I used, I fixed it and ww2ogg works fine now. Sorry for the late reply.

**Comment by qybeck** [comment]
hi @Tachiorz ，
Can you share the Lineage eternal Unpack tool for me?
